version: "3.9"

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - ./data/sql/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
# Uncomment following lines if you need to check database (ex. for debugging)
#    ports:
#      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      timeout: 5s
      retries: 3

  bux-wallet-backend:
    image: 4chain/bux-wallet-backend:latest
    environment:
      DB_HOST: 'db'
      BUX_SERVER_URL: 'https://bux.4chain.space/v1'
    env_file:
      - bux-wallet-backend.env.private
      # Maybe this will be needed to have working session with frontend proxy
    #      HTTP_SERVER_COOKIE_DOMAIN: 'localhost:3000'
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
