name: lint and test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
      fail-fast: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      - name: Run spv-wallet ESLint
        run: yarn lint
