name: lint and test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
      fail-fast: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile

      - name: Run Greencoin ESLint
        run: yarn lint
